./effRecJpsi ../../../Yield/rawdata/3_Bins/ybin ../../../Yield/rawdata/3_Bins/ptbin ../../../Yield/Jpsi/3_Result/reweight/reweight.root ../2_Rootfile/TrackTables.root ../2_Rootfile/TrackTables.root ../../../Yield/rawdata/2_Divide/2_AfterDivide/MC/Jpsi/mctn${1}_MagUp_prompt.root ../../../Yield/Jpsi/2_Rootfile/MC_after_cut/n${1}_MagUp_prompt.root ../../../Yield/rawdata/2_Divide/2_AfterDivide/MC/Jpsi/mctn${1}_MagDown_prompt.root ../../../Yield/Jpsi/2_Rootfile/MC_after_cut/n${1}_MagDown_prompt.root ../3_Result/toyEffRec/Jpsi/n${1}_prompt_${2}.root ${2} "reweightpN" "reweightpPTY"

./effRecJpsi ../../../Yield/rawdata/3_Bins/ybin ../../../Yield/rawdata/3_Bins/ptbin ../../../Yield/Jpsi/3_Result/reweight/reweight.root ../2_Rootfile/TrackTables.root ../2_Rootfile/TrackTables.root ../../../Yield/rawdata/2_Divide/2_AfterDivide/MC/Jpsi/mctn${1}_MagUp_fromb.root ../../../Yield/Jpsi/2_Rootfile/MC_after_cut/n${1}_MagUp_fromb.root ../../../Yield/rawdata/2_Divide/2_AfterDivide/MC/Jpsi/mctn${1}_MagDown_fromb.root ../../../Yield/Jpsi/2_Rootfile/MC_after_cut/n${1}_MagDown_fromb.root ../3_Result/toyEffRec/Jpsi/n${1}_fromb_${2}.root ${2}  "reweightbN" "reweightbPTY"

./effRecPsi2S ../../../Yield/rawdata/3_Bins/ybin ../../../Yield/rawdata/3_Bins/ptbin ../../../Yield/Psi2S/3_Result/reweight/reweight.root ../2_Rootfile/TrackTables.root ../2_Rootfile/TrackTables.root ../../../Yield/rawdata/2_Divide/2_AfterDivide/MC/Psi2S/mctn${1}_MagUp_prompt.root ../../../Yield/Psi2S/2_Rootfile/MC_after_cut/n${1}_MagUp_prompt.root ../../../Yield/rawdata/2_Divide/2_AfterDivide/MC/Psi2S/mctn${1}_MagDown_prompt.root ../../../Yield/Psi2S/2_Rootfile/MC_after_cut/n${1}_MagDown_prompt.root ../3_Result/toyEffRec/Psi2S/n${1}_prompt_${2}.root ${2}  "reweightpN" "reweightpPTY"

./effRecPsi2S ../../../Yield/rawdata/3_Bins/ybin ../../../Yield/rawdata/3_Bins/ptbin ../../../Yield/Psi2S/3_Result/reweight/reweight.root ../2_Rootfile/TrackTables.root ../2_Rootfile/TrackTables.root ../../../Yield/rawdata/2_Divide/2_AfterDivide/MC/Psi2S/mctn${1}_MagUp_fromb.root ../../../Yield/Psi2S/2_Rootfile/MC_after_cut/n${1}_MagUp_fromb.root ../../../Yield/rawdata/2_Divide/2_AfterDivide/MC/Psi2S/mctn${1}_MagDown_fromb.root ../../../Yield/Psi2S/2_Rootfile/MC_after_cut/n${1}_MagDown_fromb.root ../3_Result/toyEffRec/Psi2S/n${1}_fromb_${2}.root ${2}  "reweightbN" "reweightbPTY"


