#include <TStyle.h>
#include <TFile.h>
#include <TH1.h>
#include <math.h>
#include <iostream>
#include <fstream>
#include <TCanvas.h>
#include <TROOT.h>
#include <TLegend.h>
#include "0_header/lhcbStyle.h"
using namespace std;
int main(int argc, char* argv[])
{
	setLHCbStyle();
	//input
	TFile *input = TFile::Open("../4_Result/Reweight/Reweight.root");
	TH1D *SJ_N = (TH1D*)input->Get("SJ_N");
	TH1D *SP_N = (TH1D*)input->Get("SP_N");
	TH1D *DJ_N = (TH1D*)input->Get("DJ_N");
	TH1D *DP_N = (TH1D*)input->Get("DP_N");
	TH1D *SJ_hiPT = (TH1D*)input->Get("SJ_hiPT"); 
	TH1D *SP_hiPT = (TH1D*)input->Get("SP_hiPT");
	TH1D *SJ_loPT = (TH1D*)input->Get("SJ_loPT");
	TH1D *SP_loPT = (TH1D*)input->Get("SP_loPT");
	TH1D *SJ_hiY  = (TH1D*)input->Get("SJ_hiY"); 
	TH1D *SP_hiY  = (TH1D*)input->Get("SP_hiY");
	TH1D *SJ_loY  = (TH1D*)input->Get("SJ_loY");
	TH1D *SP_loY  = (TH1D*)input->Get("SP_loY");
	TH1D *DJ_hiPT = (TH1D*)input->Get("DJ_hiPT");
	TH1D *DP_hiPT = (TH1D*)input->Get("DP_hiPT");
	TH1D *DJ_loPT = (TH1D*)input->Get("DJ_loPT");
	TH1D *DP_loPT = (TH1D*)input->Get("DP_loPT");
	TH1D *DJ_hiY  = (TH1D*)input->Get("DJ_hiY");
	TH1D *DP_hiY  = (TH1D*)input->Get("DP_hiY");
	TH1D *DJ_loY  = (TH1D*)input->Get("DJ_loY");
	TH1D *DP_loY  = (TH1D*)input->Get("DP_loY");
	TH1D *wJ_N    = (TH1D*)input->Get("wJ_N");
	TH1D *wP_N    = (TH1D*)input->Get("wP_N");
	TH1D *wJ_hiPT = (TH1D*)input->Get("wJ_hiPT");
	TH1D *wJ_loPT = (TH1D*)input->Get("wJ_loPT");
	TH1D *wJ_hiY  = (TH1D*)input->Get("wJ_hiY");
	TH1D *wJ_loY  = (TH1D*)input->Get("wJ_loY");
	TH1D *wP_hiPT = (TH1D*)input->Get("wP_hiPT");
	TH1D *wP_loPT = (TH1D*)input->Get("wP_loPT");
	TH1D *wP_hiY  = (TH1D*)input->Get("wP_hiY");
	TH1D *wP_loY  = (TH1D*)input->Get("wP_loY");
	TH1D *SJ_PT = (TH1D*)input->Get("SJ_PT");
	TH1D *SP_PT = (TH1D*)input->Get("SP_PT");
	TH1D *DJ_PT = (TH1D*)input->Get("DJ_PT");
	TH1D *DP_PT = (TH1D*)input->Get("DP_PT");
	TH1D *SJ_Y = (TH1D*)input->Get("SJ_Y");
	TH1D *SP_Y = (TH1D*)input->Get("SP_Y");
	TH1D *DJ_Y = (TH1D*)input->Get("DJ_Y");
	TH1D *DP_Y = (TH1D*)input->Get("DP_Y");
	//Draw Mul. Dist. of sPlot data and MC for J and P
	TCanvas *can1 = new TCanvas("can1","can1",1200,800);
	SJ_N -> GetYaxis() -> SetRangeUser(0,0.14);
	SJ_N -> GetYaxis() -> SetTitle("Normalized");
	SJ_N -> SetStats(0);
	SJ_N -> SetTitle("sWeight data");
	SJ_N -> GetXaxis() -> SetTitle("#font[12]{N}_{bwd}^{PV}");
	SJ_N -> SetLineColor(kBlue);
	SJ_N -> SetMarkerColor(kBlue);
	SJ_N -> SetMarkerStyle(20);
	SP_N -> SetMarkerStyle(20);
	SP_N -> SetLineColor(kRed);
	SP_N -> SetMarkerColor(kRed);
	SP_N -> SetStats(0);
	SJ_N -> Draw();
	SP_N -> Draw("same");
	TLegend *leg1 = new TLegend(0.7,0.6,0.9,0.8);
	leg1 -> AddEntry(SJ_N, "J/#psi sig_sw");
	leg1 -> AddEntry(SP_N, "#psi(2S) sig_sw");
	leg1 -> Draw("same");
	can1 -> SaveAs("../5_Plots/Reweight/sWeightMul.pdf");
	can1 -> Close();
	//Draw Mul. Dist. of J and P MC
	TCanvas *can2 = new TCanvas("can2","can2",1200,800);
	DJ_N -> GetYaxis() -> SetRangeUser(0,0.12);
	DJ_N -> GetYaxis() -> SetTitle("Normalized");
	DJ_N -> SetStats(0);
	DJ_N -> SetTitle("MC");
	DJ_N -> GetXaxis() -> SetTitle("#font[12]{N}_{bwd}^{PV}");
	DJ_N -> SetLineColor(kBlue);
	DJ_N -> SetMarkerColor(kBlue);
	DJ_N -> SetMarkerStyle(20);
	DP_N -> SetMarkerStyle(20);
	DP_N -> SetLineColor(kRed);
	DP_N -> SetMarkerColor(kRed);
	DP_N -> SetStats(0);
	DJ_N -> Draw();
	DP_N -> Draw("same");
	TLegend *leg2 = new TLegend(0.7,0.6,0.9,0.8);
	leg2 -> AddEntry(DJ_N, "J/#psi MC");
	leg2 -> AddEntry(DP_N, "#psi(2S) MC");
	leg2 -> Draw("same");
	can2 -> SaveAs("../5_Plots/Reweight/MCMul.pdf");
	can2 -> Close();
	//Draw pT Dist. for high Mul. Jpsi sample
	TCanvas *can3 = new TCanvas("can3","can3",1200,800);
	TH1D *cJ_hiPT = (TH1D*)DJ_hiPT -> Clone("cJ_hiPT");
	cJ_hiPT -> Multiply(cJ_hiPT, wJ_hiPT, 1., 1., "B");
	SJ_hiPT -> GetYaxis() -> SetRangeUser(0,0.15);
	SJ_hiPT -> GetYaxis() -> SetTitle("Normalized");
	SJ_hiPT -> SetStats(0);
	SJ_hiPT -> SetTitle("High-Mul. J/#psi sWeight");
	SJ_hiPT -> GetXaxis() -> SetTitle("p_{T} (MeV/c)");
	SJ_hiPT -> SetLineColor(kBlue);
	SJ_hiPT -> SetMarkerColor(kBlue);
	SJ_hiPT -> SetMarkerStyle(20);
	DJ_hiPT -> SetMarkerStyle(20);
	DJ_hiPT -> SetLineColor(kRed);
	DJ_hiPT -> SetMarkerColor(kRed);
	DJ_hiPT -> SetStats(0);
	cJ_hiPT -> SetStats(0);
	cJ_hiPT -> SetMarkerColor(kGreen);
	cJ_hiPT -> SetMarkerStyle(20);
	cJ_hiPT -> SetMarkerSize(1.2);
	SJ_hiPT -> Draw();
	DJ_hiPT -> Draw("same");
	cJ_hiPT -> Draw("HISTP9same");
	TLegend *leg3 = new TLegend(0.55,0.6,0.85,0.8);
	leg3 -> AddEntry(SJ_hiPT, "High-Mul. J/#psi sig_sw");
	leg3 -> AddEntry(DJ_hiPT, "High-Mul. J/#psi MC");
	leg3 -> AddEntry(cJ_hiPT, "reweight", "P");
	leg3 -> Draw("same");
	can3 -> SaveAs("../5_Plots/Reweight/JpsiHighMulPT.pdf");
	can3 -> Close();
	//Draw pT Dist. for high Mul. Psi2S sample
	TCanvas *can4 = new TCanvas("can4","can4",1200,800);
	TH1D *cP_hiPT = (TH1D*)DP_hiPT -> Clone("cP_hiPT");
	cP_hiPT -> Multiply(cP_hiPT, wP_hiPT, 1., 1., "B");
	SP_hiPT -> GetYaxis() -> SetRangeUser(0,0.15);
	SP_hiPT -> GetYaxis() -> SetTitle("Normalized");
	SP_hiPT -> SetStats(0);
	SP_hiPT -> SetTitle("High-Mul. #psi sWeight");
	SP_hiPT -> GetXaxis() -> SetTitle("p_{T} (MeV/c)");
	SP_hiPT -> SetLineColor(kBlue);
	SP_hiPT -> SetMarkerColor(kBlue);
	SP_hiPT -> SetMarkerStyle(20);
	DP_hiPT -> SetMarkerStyle(20);
	DP_hiPT -> SetLineColor(kRed);
	DP_hiPT -> SetMarkerColor(kRed);
	DP_hiPT -> SetStats(0);
	cP_hiPT -> SetStats(0);
	cP_hiPT -> SetMarkerColor(kGreen);
	cP_hiPT -> SetMarkerStyle(20);
	cP_hiPT -> SetMarkerSize(1.2);
	SP_hiPT -> Draw();
	DP_hiPT -> Draw("same");
	cP_hiPT -> Draw("HISTP9same");
	TLegend *leg4 = new TLegend(0.55,0.6,0.85,0.8);
	leg4 -> AddEntry(SJ_hiPT, "High-Mul. #psi(2S) sig_sw");
	leg4 -> AddEntry(DJ_hiPT, "High-Mul. #psi(2S) MC");
	leg4 -> AddEntry(cJ_hiPT, "reweight", "P");
	leg4 -> Draw("same");
	can4 -> SaveAs("../5_Plots/Reweight/Psi2SHighMulPT.pdf");
	can4 -> Close();
	//Draw pT Dist. for low Mul. Jpsi sample
	TCanvas *can5 = new TCanvas("can5","can5",1200,800);
	TH1D *cJ_loPT = (TH1D*)DJ_loPT -> Clone("cJ_loPT");
	cJ_loPT -> Multiply(cJ_loPT, wJ_loPT, 1., 1., "B");
	SJ_loPT -> GetYaxis() -> SetRangeUser(0,0.15);
	SJ_loPT -> GetYaxis() -> SetTitle("Normalized");
	SJ_loPT -> SetStats(0);
	SJ_loPT -> SetTitle("Low-Mul. J/#psi sWeight");
	SJ_loPT -> GetXaxis() -> SetTitle("p_{T} (MeV/c)");
	SJ_loPT -> SetLineColor(kBlue);
	SJ_loPT -> SetMarkerColor(kBlue);
	SJ_loPT -> SetMarkerStyle(20);
	DJ_loPT -> SetMarkerStyle(20);
	DJ_loPT -> SetLineColor(kRed);
	DJ_loPT -> SetMarkerColor(kRed);
	DJ_loPT -> SetStats(0);
	cJ_loPT -> SetStats(0);
	cJ_loPT -> SetMarkerColor(kGreen);
	cJ_loPT -> SetMarkerStyle(20);
	cJ_loPT -> SetMarkerSize(1.2);
	SJ_loPT -> Draw();
	DJ_loPT -> Draw("same");
	cJ_loPT -> Draw("HISTP9same");
	TLegend *leg5 = new TLegend(0.55,0.6,0.85,0.8);
	leg5 -> AddEntry(SJ_loPT, "Low-Mul. J/#psi sig_sw");
	leg5 -> AddEntry(DJ_loPT, "Low-Mul. J/#psi MC");
	leg5 -> AddEntry(cJ_loPT, "reweight", "P");
	leg5 -> Draw("same");
	can5 -> SaveAs("../5_Plots/Reweight/JpsiLowMulPT.pdf");
	can5 -> Close();
	//Draw pT Dist. for low Mul. Psi2S sample
	TCanvas *can6 = new TCanvas("can6","can6",1200,800);
	TH1D *cP_loPT = (TH1D*)DP_loPT -> Clone("cP_loPT");
	cP_loPT -> Multiply(cP_loPT, wP_loPT, 1., 1., "B");
	SP_loPT -> GetYaxis() -> SetRangeUser(0,0.15);
	SP_loPT -> GetYaxis() -> SetTitle("Normalized");
	SP_loPT -> SetStats(0);
	SP_loPT -> SetTitle("Low-Mul. #psi sWeight");
	SP_loPT -> GetXaxis() -> SetTitle("p_{T} (MeV/c)");
	SP_loPT -> SetLineColor(kBlue);
	SP_loPT -> SetMarkerColor(kBlue);
	SP_loPT -> SetMarkerStyle(20);
	DP_loPT -> SetMarkerStyle(20);
	DP_loPT -> SetLineColor(kRed);
	DP_loPT -> SetMarkerColor(kRed);
	DP_loPT -> SetStats(0);
	cP_loPT -> SetStats(0);
	cP_loPT -> SetMarkerColor(kGreen);
	cP_loPT -> SetMarkerStyle(20);
	cP_loPT -> SetMarkerSize(1.2);
	SP_loPT -> Draw();
	DP_loPT -> Draw("same");
	cP_loPT -> Draw("HISTP9same");
	TLegend *leg6 = new TLegend(0.55,0.6,0.85,0.8);
	leg6 -> AddEntry(SJ_loPT, "Low-Mul. #psi(2S) sig_sw");
	leg6 -> AddEntry(DJ_loPT, "Low-Mul. #psi(2S) MC");
	leg6 -> AddEntry(cJ_loPT, "reweight", "P");
	leg6 -> Draw("same");
	can6 -> SaveAs("../5_Plots/Reweight/Psi2SLowMulPT.pdf");
	can6 -> Close();
	//Draw Y Dist. of High-Mul Jpsi sample
	TCanvas *can7 = new TCanvas("can7","can7",1200,800);
	TH1D *cJ_hiY = (TH1D*)DJ_hiY -> Clone("cJ_hiY");
	cJ_hiY -> Multiply(cJ_hiY, wJ_hiY, 1., 1., "B");
	SJ_hiY -> GetYaxis() -> SetRangeUser(0,0.23);
	SJ_hiY -> GetYaxis() -> SetTitle("Normalized");
	SJ_hiY -> SetStats(0);
	SJ_hiY -> SetTitle("High-Mul. J/#psi sWeight");
	SJ_hiY -> GetXaxis() -> SetTitle("y^{*}");
	SJ_hiY -> SetLineColor(kBlue);
	SJ_hiY -> SetMarkerColor(kBlue);
	SJ_hiY -> SetMarkerStyle(20);
	DJ_hiY -> SetMarkerStyle(20);
	DJ_hiY -> SetLineColor(kRed);
	DJ_hiY -> SetMarkerColor(kRed);
	DJ_hiY -> SetStats(0);
	cJ_hiY -> SetStats(0);
	cJ_hiY -> SetMarkerColor(kGreen);
	cJ_hiY -> SetMarkerStyle(20);
	cJ_hiY -> SetMarkerSize(1.2);
	SJ_hiY -> Draw();
	DJ_hiY -> Draw("same");
	cJ_hiY -> Draw("HISTP9same");
	TLegend *leg7 = new TLegend(0.6,0.7,0.85,0.9);
	leg7 -> AddEntry(SJ_hiY, "High-Mul. J/#psi sig_sw");
	leg7 -> AddEntry(DJ_hiY, "High-Mul. J/#psi MC");
	leg7 -> AddEntry(cJ_hiY, "reweight", "P");
	leg7 -> Draw("same");
	can7 -> SaveAs("../5_Plots/Reweight/JpsiHighMulY.pdf");
	can7 -> Close();
	//Draw Y Dist. of High-Mul Psi2S sample
	TCanvas *can8 = new TCanvas("can8","can8",1200,800);
	TH1D *cP_hiY = (TH1D*)DP_hiY -> Clone("cP_hiY");
	cP_hiY -> Multiply(cP_hiY, wP_hiY, 1., 1., "B");
	SP_hiY -> GetYaxis() -> SetRangeUser(0,0.23);
	SP_hiY -> GetYaxis() -> SetTitle("Normalized");
	SP_hiY -> SetStats(0);
	SP_hiY -> SetTitle("High-Mul. #psi(2S) sWeight");
	SP_hiY -> GetXaxis() -> SetTitle("y^{*}");
	SP_hiY -> SetLineColor(kBlue);
	SP_hiY -> SetMarkerColor(kBlue);
	SP_hiY -> SetMarkerStyle(20);
	DP_hiY -> SetMarkerStyle(20);
	DP_hiY -> SetLineColor(kRed);
	DP_hiY -> SetMarkerColor(kRed);
	DP_hiY -> SetStats(0);
	cP_hiY -> SetStats(0);
	cP_hiY -> SetMarkerColor(kGreen);
	cP_hiY -> SetMarkerStyle(20);
	cP_hiY -> SetMarkerSize(1.2);
	SP_hiY -> Draw();
	DP_hiY -> Draw("same");
	cP_hiY -> Draw("HISTP9same");
	TLegend *leg8 = new TLegend(0.6,0.7,0.85,0.9);
	leg8 -> AddEntry(SP_hiY, "High-Mul. #psi(2S) sig_sw");
	leg8 -> AddEntry(DP_hiY, "High-Mul. #psi(2S) MC");
	leg8 -> AddEntry(cP_hiY, "reweight", "P");
	leg8 -> Draw("same");
	can8 -> SaveAs("../5_Plots/Reweight/Psi2SHighMulY.pdf");
	can8 -> Close();
	//Draw Y Dist. of Low-Mul Jpsi sample
	TCanvas *can9 = new TCanvas("can9","can9",1200,800);
	TH1D *cJ_loY = (TH1D*)DJ_loY -> Clone("cJ_loY");
	cJ_loY -> Multiply(cJ_loY, wJ_loY, 1., 1., "B");
	SJ_loY -> GetYaxis() -> SetRangeUser(0,0.23);
	SJ_loY -> GetYaxis() -> SetTitle("Normalized");
	SJ_loY -> SetStats(0);
	SJ_loY -> SetTitle("Low-Mul. J/#psi sWeight");
	SJ_loY -> GetXaxis() -> SetTitle("y^{*}");
	SJ_loY -> SetLineColor(kBlue);
	SJ_loY -> SetMarkerColor(kBlue);
	SJ_loY -> SetMarkerStyle(20);
	DJ_loY -> SetMarkerStyle(20);
	DJ_loY -> SetLineColor(kRed);
	DJ_loY -> SetMarkerColor(kRed);
	DJ_loY -> SetStats(0);
	cJ_loY -> SetStats(0);
	cJ_loY -> SetMarkerColor(kGreen);
	cJ_loY -> SetMarkerStyle(20);
	cJ_loY -> SetMarkerSize(1.2);
	SJ_loY -> Draw();
	DJ_loY -> Draw("same");
	cJ_loY -> Draw("HISTP9same");
	TLegend *leg9 = new TLegend(0.6,0.7,0.85,0.9);
	leg9 -> AddEntry(SJ_loY, "Low-Mul. J/#psi sig_sw");
	leg9 -> AddEntry(DJ_loY, "Low-Mul. J/#psi MC");
	leg9 -> AddEntry(cJ_loY, "reweight", "P");
	leg9 -> Draw("same");
	can9 -> SaveAs("../5_Plots/Reweight/JpsiLowMulY.pdf");
	can9 -> Close();
	//Draw Y Dist. of Low-Mul Psi2S sample
	TCanvas *can10 = new TCanvas("can10","can10",1200,800);
	TH1D *cP_loY = (TH1D*)DP_loY -> Clone("cP_loY");
	cP_loY -> Multiply(cP_loY, wP_loY, 1., 1., "B");
	SP_loY -> GetYaxis() -> SetRangeUser(0,0.23);
	SP_loY -> GetYaxis() -> SetTitle("Normalized");
	SP_loY -> SetStats(0);
	SP_loY -> SetTitle("Low-Mul. #psi(2S) sWeight");
	SP_loY -> GetXaxis() -> SetTitle("y^{*}");
	SP_loY -> SetLineColor(kBlue);
	SP_loY -> SetMarkerColor(kBlue);
	SP_loY -> SetMarkerStyle(20);
	DP_loY -> SetMarkerStyle(20);
	DP_loY -> SetLineColor(kRed);
	DP_loY -> SetMarkerColor(kRed);
	DP_loY -> SetStats(0);
	cP_loY -> SetStats(0);
	cP_loY -> SetMarkerColor(kGreen);
	cP_loY -> SetMarkerStyle(20);
	cP_loY -> SetMarkerSize(1.2);
	SP_loY -> Draw();
	DP_loY -> Draw("same");
	cP_loY -> Draw("HISTP9same");
	TLegend *leg10 = new TLegend(0.6,0.7,0.85,0.90);
	leg10 -> AddEntry(SP_loY, "Low-Mul. #psi(2S) sig_sw");
	leg10 -> AddEntry(DP_loY, "Low-Mul. #psi(2S) MC");
	leg10 -> AddEntry(cP_loY, "reweight", "P");
	leg10 -> Draw("same");
	can10 -> SaveAs("../5_Plots/Reweight/Psi2SLowMulY.pdf");
	can10 -> Close();
	//Draw PT Dist. for both charmonia
	TCanvas *can11 = new TCanvas("can11","can11",1200,800);
	SJ_PT -> GetYaxis() -> SetRangeUser(0,0.15);
	SJ_PT -> GetYaxis() -> SetTitle("Normalized");
	SJ_PT -> SetStats(0);
	SJ_PT -> SetTitle("sWeight data");
	SJ_PT -> GetXaxis() -> SetTitle("p_{T} (MeV/c)");
	SJ_PT -> SetLineColor(kBlue);
	SJ_PT -> SetMarkerColor(kBlue);
	SJ_PT -> SetMarkerStyle(20);
	SP_PT -> SetMarkerStyle(20);
	SP_PT -> SetLineColor(kRed);
	SP_PT -> SetMarkerColor(kRed);
	SP_PT -> SetStats(0);
	SJ_PT -> Draw();
	SP_PT -> Draw("same");
	TLegend *leg11 = new TLegend(0.7,0.6,0.9,0.8);
	leg11 -> AddEntry(SJ_PT, "J/#psi sig_sw");
	leg11 -> AddEntry(SP_PT, "#psi(2S) sig_sw");
	leg11 -> Draw("same");
	can11 -> SaveAs("../5_Plots/Reweight/sWeightPT.pdf");
	can11 -> Close();
	//Draw Y Dist. for both charmonia
	TCanvas *can12 = new TCanvas("can12","can12",1200,800);
	SJ_Y -> GetYaxis() -> SetRangeUser(0,0.23);
	SJ_Y -> GetYaxis() -> SetTitle("Normalized");
	SJ_Y -> SetStats(0);
	SJ_Y -> SetTitle("sWeight data");
	SJ_Y -> GetXaxis() -> SetTitle("y^{*}");
	SJ_Y -> SetLineColor(kBlue);
	SJ_Y -> SetMarkerColor(kBlue);
	SJ_Y -> SetMarkerStyle(20);
	SP_Y -> SetMarkerStyle(20);
	SP_Y -> SetLineColor(kRed);
	SP_Y -> SetMarkerColor(kRed);
	SP_Y -> SetStats(0);
	SJ_Y -> Draw();
	SP_Y -> Draw("same");
	TLegend *leg12 = new TLegend(0.7,0.6,0.9,0.8);
	leg12 -> AddEntry(SJ_Y, "J/#psi sig_sw");
	leg12 -> AddEntry(SP_Y, "#psi(2S) sig_sw");
	leg12 -> Draw("same");
	can12 -> SaveAs("../5_Plots/Reweight/sWeightY.pdf");
	can12 -> Close();	
	return 0;
}
