groot -o ../2_Exe/CBFit CBFit.C >/dev/null 2>&1 & #
groot -o ../2_Exe/Cut Cut.C >/dev/null 2>&1 & #
groot -o ../2_Exe/Cut_MC Cut_MC.C >/dev/null 2>&1 & #
groot -o ../2_Exe/Divide Divide.C >/dev/null 2>&1 & #
groot -o ../2_Exe/Divide_FullMC Divide_FullMC.C >/dev/null 2>&1 & #
groot -o ../2_Exe/Draw_Result Draw_Result.C >/dev/null 2>&1 & #
groot -o ../2_Exe/Draw_Reweight Draw_Reweight.C >/dev/null 2>&1 & #
groot -o ../2_Exe/Draw_TwoProjMass  Draw_TwoProjMass.C  >/dev/null 2>&1 & #
groot -o ../2_Exe/Draw_TzbkgFit Draw_TzbkgFit.C >/dev/null 2>&1 & #
groot -o ../2_Exe/Draw_TwoProjTz Draw_TwoProjTz.C >/dev/null 2>&1 & #
groot -o ../2_Exe/Eff_Acc Eff_Acc.C >/dev/null 2>&1 & #
groot -o ../2_Exe/Eff_RecselPIDTrigger Eff_RecselPIDTrigger.C >/dev/null 2>&1 & #
groot -o ../2_Exe/GetEffMean GetEffMean.C >/dev/null 2>&1 & #
groot -o ../2_Exe/Reweight Reweight.C >/dev/null 2>&1 & #
groot -o ../2_Exe/SideBand SideBand.C >/dev/null 2>&1 & #
groot -o ../2_Exe/SysErr_General SysErr_General.C >/dev/null 2>&1 & #
groot -o ../2_Exe/SysErr_PIDCalibBinScheme SysErr_PIDCalibBinScheme.C >/dev/null 2>&1 & #
groot -o ../2_Exe/TwoDimFit TwoDimFit.C >/dev/null 2>&1 & #
groot -o ../2_Exe/TzbkgFit TzbkgFit.C >/dev/null 2>&1 & #
groot -o ../2_Exe/ttCBFit ttCBFit.C >/dev/null 2>&1 & #
groot -o ../2_Exe/ttMC ttMC.C >/dev/null 2>&1 & #
groot -o ../2_Exe/tisCut tisCut.C >/dev/null 2>&1 & #
groot -o ../2_Exe/tistosCut tistosCut.C >/dev/null 2>&1 & #
groot -o ../2_Exe/DrawNoNorm DrawNoNorm.C >/dev/null 2>&1 & #
groot -o ../2_Exe/DrawNorm2pp DrawNorm2pp.C >/dev/null 2>&1 & #
