./effPIDJpsi ../../../Yield/rawdata/3_Bins/ybin ../../../Yield/rawdata/3_Bins/ptbin ../../../Yield/Jpsi/3_Result/reweight/reweight.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagUp_custom_Muon_P_ETA_nSPDHits.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagDown_custom_Muon_P_ETA_nSPDHits.root ../2_Rootfile/TrackTables.root ../2_Rootfile/TrackTables.root ../../../Yield/Jpsi/2_Rootfile/MC_after_cut/n${1}_MagUp_prompt.root ../../../Yield/Jpsi/2_Rootfile/MC_after_cut/n${1}_MagDown_prompt.root ../3_Result/toyEffPID/Jpsi/n${1}_prompt_${2}.root ${2}  "reweightpN" "reweightpPTY"

./effPIDJpsi ../../../Yield/rawdata/3_Bins/ybin ../../../Yield/rawdata/3_Bins/ptbin ../../../Yield/Jpsi/3_Result/reweight/reweight.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagUp_custom_Muon_P_ETA_nSPDHits.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagDown_custom_Muon_P_ETA_nSPDHits.root ../2_Rootfile/TrackTables.root ../2_Rootfile/TrackTables.root ../../../Yield/Jpsi/2_Rootfile/MC_after_cut/n${1}_MagUp_fromb.root ../../../Yield/Jpsi/2_Rootfile/MC_after_cut/n${1}_MagDown_fromb.root ../3_Result/toyEffPID/Jpsi/n${1}_fromb_${2}.root ${2}  "reweightbN" "reweightbPTY"


./effPIDPsi2S ../../../Yield/rawdata/3_Bins/ybin ../../../Yield/rawdata/3_Bins/ptbin ../../../Yield/Psi2S/3_Result/reweight/reweight.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagUp_custom_Muon_P_ETA_nSPDHits.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagDown_custom_Muon_P_ETA_nSPDHits.root ../2_Rootfile/TrackTables.root ../2_Rootfile/TrackTables.root ../../../Yield/Psi2S/2_Rootfile/MC_after_cut/n${1}_MagUp_prompt.root ../../../Yield/Psi2S/2_Rootfile/MC_after_cut/n${1}_MagDown_prompt.root ../3_Result/toyEffPID/Psi2S/n${1}_prompt_${2}.root ${2}  "reweightpN" "reweightpPTY"

./effPIDPsi2S ../../../Yield/rawdata/3_Bins/ybin ../../../Yield/rawdata/3_Bins/ptbin ../../../Yield/Psi2S/3_Result/reweight/reweight.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagUp_custom_Muon_P_ETA_nSPDHits.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagDown_custom_Muon_P_ETA_nSPDHits.root ../2_Rootfile/TrackTables.root ../2_Rootfile/TrackTables.root ../../../Yield/Psi2S/2_Rootfile/MC_after_cut/n${1}_MagUp_fromb.root ../../../Yield/Psi2S/2_Rootfile/MC_after_cut/n${1}_MagDown_fromb.root ../3_Result/toyEffPID/Psi2S/n${1}_fromb_${2}.root ${2}  "reweightbN" "reweightbPTY"


