./Fill_JpsiInBin ../../../Yield/rawdata/3_Bins/ybin ../../../Yield/rawdata/3_Bins/ptbin ../../../Yield/Jpsi/3_Result/reweight/reweight.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagUp_custom_Muon_P_ETA_nSPDHits${2}.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagDown_custom_Muon_P_ETA_nSPDHits${2}.root ../../../Yield/rawdata/1_Rootfile/TrackCalib/Ratio_Long_P-ETA_2016_25ns.root ../../../Yield/rawdata/1_Rootfile/TrackCalib/Ratio_Long_P-ETA_2016_25ns.root ../../../Yield/Jpsi/2_Rootfile/MC_after_cut/n${1}_MagUp_prompt.root ../../../Yield/Jpsi/2_Rootfile/MC_after_cut/n${1}_MagDown_prompt.root ../3_Result/InBinVar/Jpsi/n${1}_prompt${2}.root "reweightpN" "reweightpPTY" >/dev/null 2>&1 

./Fill_JpsiInBin ../../../Yield/rawdata/3_Bins/ybin ../../../Yield/rawdata/3_Bins/ptbin ../../../Yield/Jpsi/3_Result/reweight/reweight.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagUp_custom_Muon_P_ETA_nSPDHits${2}.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagDown_custom_Muon_P_ETA_nSPDHits${2}.root ../../../Yield/rawdata/1_Rootfile/TrackCalib/Ratio_Long_P-ETA_2016_25ns.root ../../../Yield/rawdata/1_Rootfile/TrackCalib/Ratio_Long_P-ETA_2016_25ns.root ../../../Yield/Jpsi/2_Rootfile/MC_after_cut/n${1}_MagUp_fromb.root ../../../Yield/Jpsi/2_Rootfile/MC_after_cut/n${1}_MagDown_fromb.root ../3_Result/InBinVar/Jpsi/n${1}_fromb${2}.root >/dev/null 2>&1  "reweightbN" "reweightbPTY"

./Fill_Psi2SInBin ../../../Yield/rawdata/3_Bins/ybin ../../../Yield/rawdata/3_Bins/ptbin ../../../Yield/Psi2S/3_Result/reweight/reweight.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagUp_custom_Muon_P_ETA_nSPDHits${2}.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagDown_custom_Muon_P_ETA_nSPDHits${2}.root ../../../Yield/rawdata/1_Rootfile/TrackCalib/Ratio_Long_P-ETA_2016_25ns.root ../../../Yield/rawdata/1_Rootfile/TrackCalib/Ratio_Long_P-ETA_2016_25ns.root ../../../Yield/Psi2S/2_Rootfile/MC_after_cut/n${1}_MagUp_prompt.root ../../../Yield/Psi2S/2_Rootfile/MC_after_cut/n${1}_MagDown_prompt.root ../3_Result/InBinVar/Psi2S/n${1}_prompt${2}.root "reweightpN" "reweightpPTY" >/dev/null 2>&1 

./Fill_Psi2SInBin ../../../Yield/rawdata/3_Bins/ybin ../../../Yield/rawdata/3_Bins/ptbin ../../../Yield/Psi2S/3_Result/reweight/reweight.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagUp_custom_Muon_P_ETA_nSPDHits${2}.root ../../../Yield/rawdata/1_Rootfile/PIDCalib/PerfHists_Mu_Turbo16_MagDown_custom_Muon_P_ETA_nSPDHits${2}.root ../../../Yield/rawdata/1_Rootfile/TrackCalib/Ratio_Long_P-ETA_2016_25ns.root ../../../Yield/rawdata/1_Rootfile/TrackCalib/Ratio_Long_P-ETA_2016_25ns.root ../../../Yield/Psi2S/2_Rootfile/MC_after_cut/n${1}_MagUp_fromb.root ../../../Yield/Psi2S/2_Rootfile/MC_after_cut/n${1}_MagDown_fromb.root ../3_Result/InBinVar/Psi2S/n${1}_fromb${2}.root "reweightbN" "reweightbPTY" >/dev/null 2>&1 





